# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('val_name', models.CharField(blank=True, max_length=55, null=True)),
                ('alias_name', models.CharField(blank=True, max_length=55, null=True)),
                ('print_name', models.CharField(blank=True, max_length=55, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('ldc', models.BooleanField(default=False)),
                ('class_flag', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmcore.AccountGroup')),
            ],
            options={
                'db_table': 'tbl_acc_group',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
