# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmcore', '0007_auto_20171031_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bmcore.Branch'),
        ),
    ]
